name: Qodana  
  uses: github/codeql-action/upload-sarif@v2
  with:
    sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
      
- name: 'Qodana Scan'
  uses: JetBrains/qodana-action@main
  env:
    QODANA_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJvcmdhbml6YXRpb24iOiIzajA4ayIsInByb2plY3QiOiJwNUc0UCIsInRva2VuIjoienhEWU0ifQ.0plAhVjVisIjpRyTlmBART6ma5548uQfHLimIZCvzZo

jobs:
  qodana:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.1.0 
        
